### ISSUE TITLE
 请教一下rootProject中的gradle配置可以引用到version中配置的依赖么

### ISSUE THREAD

**Issue by asker517** [Flywith24/Android-Detail#2]
Hi,RT

**Comment by Flywith24** [comment]
我认为是不可以的，主要是由于 gradle 构建任务的顺序造成的。

使用 version 或者 其他 gradle 插件的形式都必须引入插件，引入后才能使用其内部定义的内容。

而使用 buildSrc 的方式则能在 rootProject 的 build.gradle 中引用 buildSrc 内部定义的内容

**Comment by asker517** [comment]
@Flywith24 搜噶 非常感谢
